title: ~tore
description: Tore Anderson's technology blog
author: Tore Anderson
email: tore@fud.no
github_username: toreanderson
twitter_username: toreanderson

theme: minima

show_excerpts: true

post_image: /images/

plugins:
  - jekyll-feed
